### ISSUE TITLE
Config file blank

### ISSUE THREAD

**Issue by shimajima** [xGinko/NetherCeiling#2]
Hello Ginko! I am trying to use the 1.3.0--1.20.1 version of NetherCeiling on my Paper 1.20.1 server. After copying the jar and starting the server, it creates a "NetherCeiling" plugin folder but the config.yml inside it is completely blank and I get the following error in the console:
`[21:53:12 ERROR]: [NetherCeiling] Failed to load config file! - Cannot invoke "io.github.thatsmusic99.configurationmaster.api.ConfigSection.getKeys(boolean)" because "section" is null
[21:53:12 WARN]: java.lang.NullPointerException: Cannot invoke "io.github.thatsmusic99.configurationmaster.api.ConfigSection.getKeys(boolean)" because "section" is null
[21:53:12 WARN]:        at NetherCeiling-1.3.0--1.20.1.jar//me.xginko.netherceiling.modules.building.LimitSpecificBlocks.<init>(LimitSpecificBlocks.java:40)
[21:53:12 WARN]:        at NetherCeiling-1.3.0--1.20.1.jar//me.xginko.netherceiling.modules.NetherCeilingModule.reloadModules(NetherCeilingModule.java:44)
[21:53:12 WARN]:        at NetherCeiling-1.3.0--1.20.1.jar//me.xginko.netherceiling.NetherCeiling.reloadConfiguration(NetherCeiling.java:97)
[21:53:12 WARN]:        at NetherCeiling-1.3.0--1.20.1.jar//me.xginko.netherceiling.NetherCeiling.reloadPlugin(NetherCeiling.java:90)
[21:53:12 WARN]:        at NetherCeiling-1.3.0--1.20.1.jar//me.xginko.netherceiling.commands.netherceiling.subcommands.ReloadSubCmd.lambda$perform$0(ReloadSubCmd.java:32)
[21:53:12 WARN]:        at io.papermc.paper.threadedregions.scheduler.FoliaAsyncScheduler$AsyncScheduledTask.run(FoliaAsyncScheduler.java:217)
[21:53:12 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[21:53:12 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[21:53:12 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1623)`

**Comment by xGinko** [comment]
Hold on, I'll fix this

**Comment by xGinko** [comment]
should be fixed in https://github.com/xGinko/NetherCeiling/releases/tag/1.3.1
